//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Net.Quic {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Net.Quic.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Only IPv4 or IPv6 are supported に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_addressfamily_notsupported {
            get {
                return ResourceManager.GetString("net_quic_addressfamily_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The remote certificate is invalid because of errors in the certificate chain: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_cert_chain_validation {
            get {
                return ResourceManager.GetString("net_quic_cert_chain_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The remote certificate was rejected by the provided RemoteCertificateValidationCallback. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_cert_custom_validation {
            get {
                return ResourceManager.GetString("net_quic_cert_custom_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection aborted by peer ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_connectionaborted {
            get {
                return ResourceManager.GetString("net_quic_connectionaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must pass loopback address and port 0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_noloopback {
            get {
                return ResourceManager.GetString("net_quic_noloopback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection is not connected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_not_connected {
            get {
                return ResourceManager.GetString("net_quic_not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QUIC is not supported on this platform. See https://aka.ms/dotnetquic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_notsupported {
            get {
                return ResourceManager.GetString("net_quic_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_operationaborted {
            get {
                return ResourceManager.GetString("net_quic_operationaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading is not allowed on stream. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_reading_notallowed {
            get {
                return ResourceManager.GetString("net_quic_reading_notallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sending has already been aborted on the stream に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_sending_aborted {
            get {
                return ResourceManager.GetString("net_quic_sending_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is not supported by System.Net.Quic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_ssl_option {
            get {
                return ResourceManager.GetString("net_quic_ssl_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream aborted by peer ({0}). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_streamaborted {
            get {
                return ResourceManager.GetString("net_quic_streamaborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection timed out. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_timeout {
            get {
                return ResourceManager.GetString("net_quic_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout can only be set to &apos;System.Threading.Timeout.Infinite&apos; or a value &gt; 0. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_timeout_use_gt_zero {
            get {
                return ResourceManager.GetString("net_quic_timeout_use_gt_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported address family of &apos;{0}&apos; for remote endpoint. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_unsupported_address_family {
            get {
                return ResourceManager.GetString("net_quic_unsupported_address_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Writing is not allowed on stream. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_quic_writing_notallowed {
            get {
                return ResourceManager.GetString("net_quic_writing_notallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application protocol list is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string net_ssl_app_protocols_invalid {
            get {
                return ResourceManager.GetString("net_ssl_app_protocols_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Net.Quic is not supported on this platform. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SystemNetQuic_PlatformNotSupported {
            get {
                return ResourceManager.GetString("SystemNetQuic_PlatformNotSupported", resourceCulture);
            }
        }
    }
}
